name: Run searches
on: push
jobs:
  uninformed-search:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
            python-version: '3.x'
      - name: Run uninformed search
        run: python3 uninformed.py
  informed-search:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
            python-version: '3.x'
      - name: Run application
        run: python3 informed.py